export const queryKeys = {
  me: ['me'] as const,
  deliveries: (filters: Record<string, unknown> = {}) => ['deliveries', filters] as const,
  delivery: (id: string) => ['delivery', id] as const,
  notifications: (page = 1) => ['notifications', page] as const,
  unreadCount: ['notifications', 'unread-count'] as const,
  conversations: (deliveryId?: string) => ['conversations', deliveryId ?? 'all'] as const,
  messages: (conversationId: string) => ['messages', conversationId] as const,
  savedAddresses: ['locations', 'saved'] as const,
  riderProfile: ['rider', 'me'] as const,
  riderEarnings: ['rider', 'earnings'] as const,
  riderDeliveries: ['rider', 'deliveries'] as const,
  riderOffers: ['rider', 'offers'] as const,
  tickets: ['support', 'tickets'] as const,
  ticket: (id: string) => ['support', 'ticket', id] as const,
  ticketMessages: (id: string) => ['support', 'ticket-messages', id] as const,
  adminOverview: ['admin', 'overview'] as const,
  adminUsers: (q: string) => ['admin', 'users', q] as const,
  adminRiders: (q: string) => ['admin', 'riders', q] as const,
  adminDeliveries: (filters: Record<string, unknown> = {}) => ['admin', 'deliveries', filters] as const,
};
